name: Generate Checksum for Release

on:
  release:
    types: [published]

jobs:
  generate-checksum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate checksum.txt
        run: |
          echo "grpctestify.sh $(sha256sum grpctestify.sh | awk '{print $1}')" > checksum.txt

      - name: Upload checksum.txt to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./checksum.txt
          asset_name: checksum.txt
          asset_content_type: text/plain
