name: Generate Checksum for Release

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  generate-checksum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate checksum.txt
        run: |
          echo "grpctestify.sh $(sha256sum grpctestify.sh | awk '{print $1}')" > checksum.txt

      - name: Upload checksum.txt to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: checksum.txt
          tag_name: ${{ github.event.release.tag_name }}
          body: "Checksum file for verification"

