name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build client-server
        run: |
          cd client-server
          go build -o /tmp/client-server .
          chmod +x /tmp/client-server
          cd -

      # macOS-specific Docker setup
      - name: Setup Docker on macOS
        if: matrix.os == 'macos-13'
        uses: douglascamata/setup-docker-macos-action@v1.0.0

      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update && sudo apt-get install -y jq
          else
            brew install jq
          fi
          go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
          grpcurl --version

      - name: Run client-server
        run: |
          /tmp/client-server &
          echo $! > /tmp/client-server.pid

      - name: Start Greeter server
        run: |
          make up CONTAINER_NAME=greeter-server-1 
          make up CONTAINER_NAME=greeter-server-2 SERVER_PORT=4771  
          sleep 5
      
      - name: Change permissions
        run: |
          chmod +x grpctestify.sh

      - name: Run tests
        run: |
          ./grpctestify.sh --verbose tests/

      - name: Run optional address tests
        run: |
          DEFAULT_ADDRESS=localhost:4771 ./grpctestify.sh --verbose tests/greeter_optional-address.gctf

      - name: Run streams tests
        run: |
          DEFAULT_ADDRESS=localhost:4771 ./grpctestify.sh --verbose client-server/tests/

      - name: Cleanup
        run: |
          docker rm -f greeter-server-1 greeter-server-2 || true
          kill $(cat /tmp/client-server.pid) || true
          rm /tmp/client-server.pid || true
