name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build client-server
        run: |
          cd client-server
          go build -o /tmp/client-server .
          chmod +x /tmp/client-server
          cd -

      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update && sudo apt-get install -y jq
          else
            brew install jq
          fi
          go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
          grpcurl --version

      - name: Run client-server
        run: |
          /tmp/client-server &
          echo $! > /tmp/client-server.pid

      - name: Start Greeter server
        run: |
          HTTP_PORT=4790 go run github.com/bavix/gripmock/v3@v3.2.15 --stub ./stubs ./api &
          echo $! > /tmp/server1.pid
          go run github.com/bavix/gripmock/v3@v3.2.15 check --silent
          GRPC_PORT=4771 HTTP_PORT=4791 go run github.com/bavix/gripmock/v3@v3.2.15 --stub ./stubs ./api &
          echo $! > /tmp/server2.pid
          GRPC_PORT=4771 go run github.com/bavix/gripmock/v3@v3.2.15 check --silent
      
      - name: Change permissions
        run: |
          chmod +x grpctestify.sh

      - name: Run tests
        run: |
          ./grpctestify.sh --verbose tests/

      - name: Run optional address tests
        run: |
          DEFAULT_ADDRESS=localhost:4771 ./grpctestify.sh --verbose tests/greeter_optional-address.gctf

      - name: Run streams tests
        run: |
          DEFAULT_ADDRESS=localhost:4771 ./grpctestify.sh --verbose client-server/tests/

      - name: Cleanup
        run: |
          kill $(cat /tmp/client-server.pid) || true
          kill $(cat /tmp/server1.pid) || true
          kill $(cat /tmp/server2.pid) || true
          rm /tmp/client-server.pid /tmp/server1.pid /tmp/server2.pid || true
